DEF(Begin)
DEF(End)
DEF(GetString)
DEF(GetError)
DEF(Enable)
DEF(GetIntegerv)
DEF(Hint)
DEF(PixelStorei)
DEF(ClearColor)
DEF(Clear)
DEF(Viewport)
DEF(MatrixMode)
DEF(LoadIdentity)
DEF(Ortho)
DEF(Vertex2d)
DEF(Color3f)
DEF(Color4f)

DEF(CompressedTexImage3D)
DEF(CompressedTexImage2D)
DEF(CompressedTexImage1D)
DEF(CompressedTexSubImage3D)
DEF(CompressedTexSubImage2D)
DEF(CompressedTexSubImage1D)
DEF(GetCompressedTexImage)

DEF2(CompressedTexImage3D, CompressedTexImage3DARB)
DEF2(CompressedTexImage2D, CompressedTexImage2DARB)
DEF2(CompressedTexImage1D, CompressedTexImage1DARB)
DEF2(CompressedTexSubImage3D, CompressedTexSubImage3DARB)
DEF2(CompressedTexSubImage2D, CompressedTexSubImage2DARB)
DEF2(CompressedTexSubImage1D, CompressedTexSubImage1DARB)
DEF2(GetCompressedTexImage, GetCompressedTexImageARB)

DEF2(CompressedTexImage3D, CompressedTexImage3DEXT)
DEF2(CompressedTexImage2D, CompressedTexImage2DEXT)
DEF2(CompressedTexImage1D, CompressedTexImage1DEXT)
DEF2(CompressedTexSubImage3D, CompressedTexSubImage3DEXT)
DEF2(CompressedTexSubImage2D, CompressedTexSubImage2DEXT)
DEF2(CompressedTexSubImage1D, CompressedTexSubImage1DEXT)
DEF2(GetCompressedTexImage, GetCompressedTexImageEXT)


