DEF(TexImage2D)

DEF(BindBuffer)
DEF(DeleteBuffers)
DEF(GenBuffers)
DEF(IsBuffer)
DEF(BufferData)
DEF(BufferSubData)
DEF(GetBufferSubData)
DEF(MapBuffer)
DEF(UnmapBuffer)
DEF(GetBufferParameteriv)
DEF(GetBufferPointerv)

DEF2(BindBuffer, BindBufferARB)
DEF2(DeleteBuffers, DeleteBuffersARB)
DEF2(GenBuffers, GenBuffersARB)
DEF2(IsBuffer, IsBufferARB)
DEF2(BufferData, BufferDataARB)
DEF2(BufferSubData, BufferSubDataARB)
DEF2(GetBufferSubData, GetBufferSubDataARB)
DEF2(MapBuffer, MapBufferARB)
DEF2(UnmapBuffer, UnmapBufferARB)
DEF2(GetBufferParameteriv, GetBufferParameterivARB)
DEF2(GetBufferPointerv, GetBufferPointervARB)

DEF2(BindBuffer, BindBufferEXT)
DEF2(DeleteBuffers, DeleteBuffersEXT)
DEF2(GenBuffers, GenBuffersEXT)
DEF2(IsBuffer, IsBufferEXT)
DEF2(BufferData, BufferDataEXT)
DEF2(BufferSubData, BufferSubDataEXT)
DEF2(GetBufferSubData, GetBufferSubDataEXT)
DEF2(MapBuffer, MapBufferEXT)
DEF2(UnmapBuffer, UnmapBufferEXT)
DEF2(GetBufferParameteriv, GetBufferParameterivEXT)
DEF2(GetBufferPointerv, GetBufferPointervEXT)


