/* nr: 11 */
/* sz: 16 */
static struct dict_entry_t bitmap_resource_functionors_table[16] = {
	[1] = {
		.key = "GIF",
		.hash = 0x986f7051,
		.data = {.ptr = NULL},
	},
	[2] = {
		.key = "BMP",
		.hash = 0x65cc92b2,
		.data = {.ptr = NULL},
	},
	[4] = {
		.key = "PNM",
		.hash = 0xab3881f4,
		.data = {.ptr = NULL},
	},
	[5] = {
		.key = "XCF",
		.hash = 0x906a22e4,
		.data = {.ptr = NULL},
	},
	[6] = {
		.key = "XPM",
		.hash = 0x91308046,
		.data = {.ptr = NULL},
	},
	[7] = {
		.key = "PNG",
		.hash = 0xab3881fe,
		.data = {.ptr = NULL},
	},
	[10] = {
		.key = "TIF",
		.hash = 0x99143e1a,
		.data = {.ptr = NULL},
	},
	[11] = {
		.key = "PCX",
		.hash = 0xaa90a882,
		.data = {.ptr = NULL},
	},
	[12] = {
		.key = "LBM",
		.hash = 0xbb653a3c,
		.data = {.ptr = NULL},
	},
	[13] = {
		.key = "XV",
		.hash = 0x2052535c,
		.data = {.ptr = NULL},
	},
	[14] = {
		.key = "JPG",
		.hash = 0x42c47bee,
		.data = {.ptr = NULL},
	},
};

static struct dict_t bitmap_resource_functionors_dict = {
	.nr_fill = 11,
	.nr_used = 11,
	.mask = 15,
	.flags = DICT_FL_STRKEY | DICT_FL_FIXED,
	.private = STRDICT_FL_FIXED,
	.ptable = bitmap_resource_functionors_table,
};

/* generated by: */
/* ./src/common/gen_static_dict 11 16 BMP GIF JPG LBM PCX PNG PNM TIF XCF XPM XV bitmap_resource_functionors */
