/* nr: 1 */
/* sz: 8 */
static struct dict_entry_t io_functionors_table[8] = {
	[6] = {
		.key = "FILE",
		.hash = 0xc3fe6a16,
		.data = {.ptr = &file_io_functionor},
	},
};

static struct dict_t io_functionors_dict = {
	.nr_fill = 1,
	.nr_used = 1,
	.mask = 7,
	.flags = DICT_FL_STRKEY | DICT_FL_FIXED,
	.private = STRDICT_FL_FIXED,
	.ptable = io_functionors_table,
};

/* generated by: */
/* ./src/common/gen_static_dict 1 8 FILE=&file_io_functionor io_functionors */
