/* nr: 2 */
/* sz: 8 */
static struct dict_entry_t io_functionors_table[8] = {
	[0] = {
		.key = "XP3",
		.hash = 0x91308038,
		.data = {.ptr = &xp3_io_functionor},
	},
	[6] = {
		.key = "FILE",
		.hash = 0xc3fe6a16,
		.data = {.ptr = &file_io_functionor},
	},
};

static struct dict_t io_functionors_dict = {
	.nr_fill = 2,
	.nr_used = 2,
	.mask = 7,
	.flags = DICT_FL_STRKEY | DICT_FL_FIXED,
	.private = STRDICT_FL_FIXED,
	.ptable = io_functionors_table,
};

/* generated by: */
/* ./src/common/gen_static_dict 2 8 FILE=&file_io_functionor XP3=&xp3_io_functionor io_functionors */
